# -- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES * B.PRICE) AS TOTOAL_SALSE
FROM AUTHOR A
JOIN BOOK B
    ON A.AUTHOR_ID=B.AUTHOR_ID
JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
      FROM BOOK_SALES S
      WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
      GROUP BY BOOK_ID ) S
    ON B.BOOK_ID=S.BOOK_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;



# SELECT AUTHOR.AUTHOR_ID,AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
# FROM BOOK_SALES
# INNER JOIN BOOK
#     ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
# INNER JOIN AUTHOR
#     ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID
# WHERE LEFT(SALES_DATE,7) = '2022-01'
# GROUP BY AUTHOR_ID, CATEGORY
# ORDER BY AUTHOR.AUTHOR_ID, CATEGORY DESC