-- 코드를 입력하세요
SELECT RH.CAR_ID
FROM (SELECT CAR_ID 
      FROM CAR_RENTAL_COMPANY_CAR 
     WHERE CAR_TYPE='세단') CC
JOIN (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
     WHERE LEFT(START_DATE, 7)='2022-10'
     ) RH
    ON CC.CAR_ID= RH.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;