-- 코드를 작성해주세요
SELECT INFO.ID, NAME.FISH_NAME, INFO.LENGTH
FROM (
    SELECT *, MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_LEN
    FROM FISH_INFO   
     ) INFO
JOIN FISH_NAME_INFO NAME
ON INFO.FISH_TYPE=NAME.FISH_TYPE
WHERE INFO.LENGTH = INFO.MAX_LEN
ORDER BY INFO.ID ASC;