-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B
JOIN ( SELECT * 
       FROM BOOK_SALES 
       WHERE LEFT(SALES_DATE, 7) ='2022-01') BS
ON B.BOOK_ID = BS.BOOK_ID
GROUP BY CATEGORY
# HAVING LEFT(SALES_DATE, 7)='2022-01'
ORDER BY CATEGORY ASC;